#fills tables with dummy data for testing

insert into login values('batman','batman123','batman@gmail.com','43');
insert into login values('robin','robin123','robin@gmail.com','34');

insert into user values('batman');
insert into user values('robin');

insert into books values(12, 'Harper Lee', 'To Kill a Mockingbird', 'fiction');
insert into books values(31, 'J. R. R. Tolkien', 'The Lord of the Rings', 'fantasy');
insert into books values(43, 'Paulo Coelho', 'The Alchemist', 'fantasy');
insert into books values(52, 'J. K Rowling', "Harry Potter and the Philosopher's Stone", 'fantasty');
insert into books values(53, 'J. K Rowling', "Harry Potter and the Chamber of Secrets", 'fantasty');
insert into books values(54, 'J. K Rowling', "Harry Potter and the Prisoner of Azkaban", 'fantasty');
insert into books values(55, 'J. K Rowling', "Harry Potter and the Goblet of Fire", 'fantasty');
insert into books values(56, 'J. K Rowling', "Harry Potter and the Order of the Phoenix", 'fantasty');
insert into books values(57, 'J. K Rowling', "Harry Potter and the Half-Blood Prince", 'fantasty');
insert into books values(58, 'J. K Rowling', "Harry Potter and the Deathly Hallows", 'fantasty');

insert into post (username, text1, book_id) values ('batman', 'Boo Radley is my favorite character', 12);
insert into post (username, text1, book_id) values ('robin', 'I enjoyed chapter 7', 12);
insert into post (username, text1, book_id) values ('batman',  'I liked the use of metaphor in chapter 8', 12);
insert into post (username, text1, book_id) values ('batman', 'There was too much imagery in chapter 2', 12);
insert into post (username, text1, book_id) values ('robin', 'I disliked chapter 5', 12);

#complex queries for demo
use book_club;
(SELECT count(*), book_id FROM post WHERE username = 'batman' GROUP BY book_id) UNION (SELECT count(*), book_id FROM post WHERE username = 'robin' GROUP BY book_id);
SELECT count(*), b.book_title FROM books b NATURAL JOIN Reads_ r WHERE b.author LIKE "%Rowling%" AND r.page_number >= 50 GROUP BY b.book_title; 



Insert into books values('127','Alexandre Dumas','Count of Monte Cristo','Literary Fiction');
Insert into books values('56','Thomas Hardy','Far from the Madding Crowd','General Fiction');
Insert into books values('66','Henry Fielding','History of Tom Jones, A Foundling','Historical Fiction');
Insert into books values('61','Jules Verne','Mysterious Island','Science Fiction');
Insert into books values('21',' Nat Love','Life and Adventures of Nat Love','Biography & Autobiography');
Insert into books values('26','Bai Li 李白','Drinking Alone by Moonlight','Poetry');
Insert into books values('89','Alexandre Dumas','Twenty Years After','Action & Adventure Fiction');
Insert into books values('42','John Bagnell Bury','History of Greece to the Death of Alexander the Great, Vol I','Antiquity');
Insert into books values('5','Anton Chekhov','Tales of Chekhov Vol. 01','Short Stories');
Insert into books values('23','L. Frank Baum','Rinkitink in Oz','Action & Adventure');
Insert into books values('18','Laurence Housman','Englishwoman's Love-Letters','Family & Relationships');
Insert into books values('57','Isabella L. Bird','Unbeaten Tracks in Japan','*Non-fiction');
Insert into books values('2',' General Sir John Miller Adye','Indian Frontier Policy, an Historical Sketch','*Non-fiction');
Insert into books values('22','Rudyard Kipling','Kim','Action & Adventure');
Insert into books values('44',' Alexis de Tocqueville','Democracy in America Vol. I','*Non-fiction');
Insert into books values('17','Kenneth Grahame','Golden Age','Children's Fiction');
Insert into books values('35',' Saki','Beasts and Super-Beasts','Short Stories');
Insert into books values('9',' Various','Short Nonfiction Collection Vol. 001','*Non-fiction');
Insert into books values('20','P. G. Wodehouse','Mike: A Public School Story','Humorous Fiction');
Insert into books values('24','George MacDonald','Phantastes: A Faerie Romance for Men and Women','Myths, Legends & Fairy Tales');
Insert into books values('40','Edgar Wallace','Angel of Terror','Detective Fiction');
Insert into books values('54','Henrietta Elizabeth Marshall','Our Island Story, Part 1','Children's Fiction');
Insert into books values('37','Lucy Maud Montgomery','Anne of Green Gables (version 3)','Children's Fiction');
Insert into books values('11','Israel Zangwill','Big Bow Mystery','Detective Fiction');
Insert into books values('116','William Allan Neilson','Junior Classics Volume 1: Fairy and Wonder Tales','Children's Fiction');
Insert into books values('29','Willa Sibert Cather','O Pioneers!','General Fiction');
Insert into books values('41','George Manville Fenn','Bunyip Land','Children's Fiction');
Insert into books values('60','Hugh Lofting','Voyages of Doctor Dolittle','Children's Fiction');
Insert into books values('80','Friedrich Nietzsche','Thus Spake Zarathustra: A Book for All and None','*Non-fiction');
Insert into books values('6',' John L. Cotter','New Discoveries at Jamestown','*Non-fiction');
Insert into books values('68','Alexandre Dumas','Three Musketeers','Action & Adventure Fiction');
Insert into books values('7',' Charles W. Colby','Chronicles of Canada Volume 07 - The Fighting Governer: A Chronicle of Frontenac','Early Modern');
Insert into books values('0',' American Standard Version','Bible (ASV) NT 26: Epistle of Jude','Bibles');
Insert into books values('15',' John Wesley Powell','Canyons of the Colorado','*Non-fiction');
Insert into books values('33','George Barr McCutcheon','Brewster's Millions','Humorous Fiction');
Insert into books values('38','Anna Katharine Green','Leavenworth Case','Detective Fiction');
Insert into books values('8',' Alfred Russel Wallace','Is Mars Habitable?','*Non-fiction');
Insert into books values('4','Elizabeth Barrett Browning','Drama of Exile','Myths, Legends & Fairy Tales');
Insert into books values('3',' Plato (Πλάτων)','Apology of Socrates','*Non-fiction');
Insert into books values('48','Thomas Hardy','Return of the Native','General Fiction');
Insert into books values('16','Charles Kingsley','Water-Babies','Action & Adventure');
Insert into books values('14','Bertrand Russell','Problems of Philosophy','*Non-fiction');
Insert into books values('19',' Various','Short Poetry Collection 042','Poetry');
Insert into books values('10',' Benjamin King','Summer's Afternoon','Poetry');
Insert into books values('28','P. G. Wodehouse','Psmith, Journalist','Humorous Fiction');
Insert into books values('30','Baroness Emma Orczy','Scarlet Pimpernel (version 3 dramatic reading)','Action & Adventure Fiction');
Insert into books values('12','Sarah Orne Jewett','Deephaven','General Fiction');
Insert into books values('46','Edward Gibbon','History of the Decline and Fall of the Roman Empire Vol. IV','*Non-fiction');
Insert into books values('36','Amelia Ann Blanford Edwards','Untrodden Peaks and Unfrequented Valleys','Travel & Geography');
Insert into books values('34','John Galsworthy','To Let (Forsyte Saga Vol. 3)','General Fiction');
Insert into books values('13',' Zitkala-Sa','Old Indian Legends','Myths, Legends & Fairy Tales');
Insert into books values('31','Sir Walter Scott','Talisman','Action & Adventure Fiction');
Insert into books values('39','Mary Elizabeth Braddon','Lady Audley's Secret','Published 1800 -1900');
Insert into books values('1',' Sarah Cory Rippey','Goody-Naughty Book','Children's Fiction');
Insert into books values('67','Charles Dickens','Our Mutual Friend','General Fiction');
Insert into books values('245','Edgar Lee Masters','Spoon River Anthology','Poetry');
Insert into books values('25','Sir Arthur Conan Doyle','Return of Sherlock Holmes','Detective Fiction');
Insert into books values('45','Thornton W. Burgess','Burgess Bird Book for Children','Science');
Insert into books values('52',' Frank Lewis Dyer','Edison, His Life and Inventions','*Non-fiction');
Insert into books values('62',' Jacob & Wilhelm Grimm','Grimms' Fairy Tales','Children's Fiction');
Insert into books values('47','Charles Darwin','Voyage of the Beagle','*Non-fiction');
Insert into books values('51',' Elizabeth Cleghorn Gaskell','North and South','General Fiction');
Insert into books values('43','Elizabeth Barrett Browning','Sonnets from the Portuguese','Poetry');
Insert into books values('99','Anthony Trollope','Way We Live Now','Literary Fiction');
Insert into books values('53','Anne Brontë','Tenant of Wildfell Hall','Literary Fiction');
Insert into books values('27','Bret Harte','Selected Stories of Bret Harte','Short Stories');
Insert into books values('49',' Louis Ginzberg','Legends of the Jews, Volume 1','Religion');
Insert into books values('164',' Grenville Kleiser','Fifteen Thousand Useful Phrases','Reference');
Insert into books values('69',' Helen Fryer','Esperanto Teacher','Language learning');
Insert into books values('84',' Alexander Hamilton','Federalist Papers','Political Science');
Insert into books values('63','Mark Twain','Life on the Mississippi','Nature');
Insert into books values('95','Fyodor Dostoyevsky','Brothers Karamazov','Published 1800 -1900');
Insert into books values('77','Ann Radcliffe','Mysteries of Udolpho','General Fiction');
Insert into books values('85','Julian of Norwich','Revelations of Divine Love','Christianity - Other');
Insert into books values('65','Charles Dickens','Life And Adventures Of Nicholas Nickleby','General Fiction');
Insert into books values('58','Edward Gibbon','History of the Decline and Fall of the Roman Empire Vol. II','*Non-fiction');
Insert into books values('70','Victor Hugo','Misérables Vol. 1','Literary Fiction');
Insert into books values('102',' Saint Ambrose','On the Duties of the Clergy','Christianity - Other');
Insert into books values('32','Harold MacGrath','Drums of Jeopardy','Horror & Supernatural Fiction');
Insert into books values('81','Mark Twain','Roughing It','Travel & Geography');
Insert into books values('72','Charles Dickens','Old Curiosity Shop','Published 1800 -1900');
Insert into books values('75','Charles Dickens','Life and Adventures of Martin Chuzzlewit','Satire');
Insert into books values('55','George Eliot','Adam Bede','Romance');
Insert into books values('79','Anthony Trollope','Can You Forgive Her?','Historical Fiction');
Insert into books values('59','Anne Brontë','Selected Poems by Currer, Ellis and Acton Bell','Poetry');
Insert into books values('74','Amelia Ann Blanford Edwards','Thousand Miles up the Nile','*Non-fiction');
Insert into books values('107',' Mrs. Isabella Beeton','Book of Household Management','Animals');