#fills tables with data

use book_club;

Insert into books values('56','Thomas Hardy','Far from the Madding Crowd','General Fiction');
Insert into books values('66','Henry Fielding','History of Tom Jones, A Foundling','Historical Fiction');
Insert into books values('21',' Nat Love','Life and Adventures of Nat Love','Biography & Autobiography');
Insert into books values('26','Bai Li','Drinking Alone by Moonlight','Poetry');
Insert into books values('89','Alexandre Dumas','Twenty Years After','Action & Adventure Fiction');
Insert into books values('42','John Bagnell Bury','History of Greece to the Death of Alexander the Great, Vol I','Antiquity');
Insert into books values('5','Anton Chekhov','Tales of Chekhov Vol. 01','Short Stories');
Insert into books values('23','L. Frank Baum','Rinkitink in Oz','Action & Adventure');
Insert into books values('18','Laurence Housman','Englishwomans Love-Letters','Family & Relationships');
Insert into books values('57','Isabella L. Bird','Unbeaten Tracks in Japan','*Non-fiction');
Insert into books values('2',' General Sir John Miller Adye','Indian Frontier Policy, an Historical Sketch','*Non-fiction');
Insert into books values('22','Rudyard Kipling','Kim','Action & Adventure');
Insert into books values('44',' Alexis de Tocqueville','Democracy in America Vol. I','*Non-fiction');
Insert into books values('17','Kenneth Grahame','Golden Age','Childrens Fiction');
Insert into books values('35',' Saki','Beasts and Super-Beasts','Short Stories');
Insert into books values('9',' Various','Short Nonfiction Collection Vol. 001','*Non-fiction');
Insert into books values('20','P. G. Wodehouse','Mike: A Public School Story','Humorous Fiction');
Insert into books values('24','George MacDonald','Phantastes: A Faerie Romance for Men and Women','Myths, Legends & Fairy Tales');
Insert into books values('40','Edgar Wallace','Angel of Terror','Detective Fiction');
Insert into books values('54','Henrietta Elizabeth Marshall','Our Island Story, Part 1','Childrens Fiction');
Insert into books values('11','Israel Zangwill','Big Bow Mystery','Detective Fiction');
Insert into books values('116','William Allan Neilson','Junior Classics Volume 1: Fairy and Wonder Tales','Childrens Fiction');
Insert into books values('29','Willa Sibert Cather','O Pioneers!','General Fiction');
Insert into books values('41','George Manville Fenn','Bunyip Land','Childrens Fiction');
Insert into books values('60','Hugh Lofting','Voyages of Doctor Dolittle','Childrens Fiction');
Insert into books values('80','Friedrich Nietzsche','Thus Spake Zarathustra: A Book for All and None','*Non-fiction');
Insert into books values('6',' John L. Cotter','New Discoveries at Jamestown','*Non-fiction');
Insert into books values('7',' Charles W. Colby','Chronicles of Canada Volume 07 - The Fighting Governer: A Chronicle of Frontenac','Early Modern');
Insert into books values('0',' American Standard Version','Bible (ASV) NT 26: Epistle of Jude','Bibles');
Insert into books values('15',' John Wesley Powell','Canyons of the Colorado','*Non-fiction');
Insert into books values('33','George Barr McCutcheon','Brewsters Millions','Humorous Fiction');
Insert into books values('38','Anna Katharine Green','Leavenworth Case','Detective Fiction');
Insert into books values('8',' Alfred Russel Wallace','Is Mars Habitable?','*Non-fiction');
Insert into books values('4','Elizabeth Barrett Browning','Drama of Exile','Myths, Legends & Fairy Tales');
Insert into books values('3',' Plato','Apology of Socrates','*Non-fiction');
Insert into books values('48','Thomas Hardy','Return of the Native','General Fiction');
Insert into books values('16','Charles Kingsley','Water-Babies','Action & Adventure');
Insert into books values('14','Bertrand Russell','Problems of Philosophy','*Non-fiction');
Insert into books values('19',' Various','Short Poetry Collection 042','Poetry');
Insert into books values('10',' Benjamin King','Summers Afternoon','Poetry');
Insert into books values('28','P. G. Wodehouse','Psmith, Journalist','Humorous Fiction');
Insert into books values('30','Baroness Emma Orczy','Scarlet Pimpernel (version 3 dramatic reading)','Action & Adventure Fiction');
Insert into books values('12','Sarah Orne Jewett','Deephaven','General Fiction');
Insert into books values('46','Edward Gibbon','History of the Decline and Fall of the Roman Empire Vol. IV','*Non-fiction');
Insert into books values('36','Amelia Ann Blanford Edwards','Untrodden Peaks and Unfrequented Valleys','Travel & Geography');
Insert into books values('34','John Galsworthy','To Let (Forsyte Saga Vol. 3)','General Fiction');
Insert into books values('13',' Zitkala-Sa','Old Indian Legends','Myths, Legends & Fairy Tales');
Insert into books values('31','Sir Walter Scott','Talisman','Action & Adventure Fiction');
Insert into books values('39','Mary Elizabeth Braddon','Lady Audleys Secret','Published 1800 -1900');
Insert into books values('1',' Sarah Cory Rippey','Goody-Naughty Book','Childrens Fiction');
Insert into books values('67','Charles Dickens','Our Mutual Friend','General Fiction');
Insert into books values('245','Edgar Lee Masters','Spoon River Anthology','Poetry');
Insert into books values('45','Thornton W. Burgess','Burgess Bird Book for Children','Science');
Insert into books values('52',' Frank Lewis Dyer','Edison, His Life and Inventions','*Non-fiction');
Insert into books values('62',' Jacob & Wilhelm Grimm','Grimms Fairy Tales','Childrens Fiction');
Insert into books values('47','Charles Darwin','Voyage of the Beagle','*Non-fiction');
Insert into books values('51',' Elizabeth Cleghorn Gaskell','North and South','General Fiction');
Insert into books values('43','Elizabeth Barrett Browning','Sonnets from the Portuguese','Poetry');
Insert into books values('99','Anthony Trollope','Way We Live Now','Literary Fiction');
Insert into books values('53','Anne Brontë','Tenant of Wildfell Hall','Literary Fiction');
Insert into books values('27','Bret Harte','Selected Stories of Bret Harte','Short Stories');
Insert into books values('49',' Louis Ginzberg','Legends of the Jews, Volume 1','Religion');
Insert into books values('164',' Grenville Kleiser','Fifteen Thousand Useful Phrases','Reference');
Insert into books values('69',' Helen Fryer','Esperanto Teacher','Language learning');
Insert into books values('84',' Alexander Hamilton','Federalist Papers','Political Science');
Insert into books values('95','Fyodor Dostoyevsky','Brothers Karamazov','Published 1800 -1900');
Insert into books values('77','Ann Radcliffe','Mysteries of Udolpho','General Fiction');
Insert into books values('85','Julian of Norwich','Revelations of Divine Love','Christianity - Other');
Insert into books values('65','Charles Dickens','Life And Adventures Of Nicholas Nickleby','General Fiction');
Insert into books values('58','Edward Gibbon','History of the Decline and Fall of the Roman Empire Vol. II','*Non-fiction');
Insert into books values('70','Victor Hugo','Misérables Vol. 1','Literary Fiction');
Insert into books values('102',' Saint Ambrose','On the Duties of the Clergy','Christianity - Other');
Insert into books values('32','Harold MacGrath','Drums of Jeopardy','Horror & Supernatural Fiction');
Insert into books values('81','Mark Twain','Roughing It','Travel & Geography');
Insert into books values('72','Charles Dickens','Old Curiosity Shop','Published 1800 -1900');
Insert into books values('75','Charles Dickens','Life and Adventures of Martin Chuzzlewit','Satire');
Insert into books values('55','George Eliot','Adam Bede','Romance');
Insert into books values('79','Anthony Trollope','Can You Forgive Her?','Historical Fiction');
Insert into books values('59','Anne Brontë','Selected Poems by Currer, Ellis and Acton Bell','Poetry');
Insert into books values('74','Amelia Ann Blanford Edwards','Thousand Miles up the Nile','*Non-fiction');
Insert into books values('107',' Mrs. Isabella Beeton','Book of Household Management','Animals');

#complex queries for demo
#(SELECT count(*), book_id FROM post WHERE username = 'batman' GROUP BY book_id) UNION (SELECT count(*), book_id FROM post WHERE username = 'robin' GROUP BY book_id);
#SELECT count(*), b.book_title FROM books b NATURAL JOIN Reads_ r WHERE b.author LIKE "%Rowling%" AND r.page_number >= 50 GROUP BY b.book_title; 

#real data from suervey of users
Insert into books values('367', ' William Shakespeare', 'Romeo and Juliet', 'historyPlaysEnglish literature, study and teaching');
Insert into books values('368', ' Arthur Conan Doyle', 'The Adventures of Sherlock Holmes', 'ConclusionspenniesConfederate States Armydetective fictionthumbs');
Insert into books values('369', ' Jane Austen', 'Pride and Prejudice', 'English');
Insert into books values('370', ' Ivan Sergeyevich Turgenev', 'First Love', '');
Insert into books values('371', ' Solomon Northup', 'Twelve Years a Slave', 'Slavery, united states, historySlaves' 'writingsKidnapping victimsSlaves, united statesAccessible book');
Insert into books values('372', ' Sun Tzu', 'The Art of War', 'CollectiblesCatalogsWorld War, 1914-1918Soldiers as artistsArt and the war');
Insert into books values('373', ' Bram Stoker', 'Dracula', 'Fiction, ghostEnglish language');
Insert into books values('374', ' Yei Theodora Ozaki', 'Japanese Fairy Tales', 'Fairy talesChildrens fictionFolkloreFiction');
Insert into books values('375', ' H. G. Wells', 'Tales of Space and Time', 'Accessible bookFictionScience FictionEnglish Science fictionClassic Literature');
Insert into books values('376', ' Frances Hodgson Burnett', 'The Secret Garden', 'Mystery and detective storiesSchoolsFictionBoarding schools');
Insert into books values('377', ' Edgar Allan Poe', 'The Black Cat', 'FictionMan-woman relationshipsContemporary WomenAccessible bookFamily Life');
Insert into books values('378', ' Sigmund Freud', 'Dream Psychology', 'PsychologyPsicoana lisisAccessible bookNonfictionPsychoanalysis');
Insert into books values('379', ' Edgar Allan Poe', 'The Power of Words', 'Incarnate Word College (San Antonio, Tex.)');
Insert into books values('380', ' Louisa May Alcott', 'Little Women', 'Social lifeConduct of lifeAccessible bookMothers and daughters, fictionFiction');
Insert into books values('381', ' Margaret Cavendish', 'The Blazing World', 'Women artists, fictionAccessible bookProtected DAISYFiction, mystery & detective');
Insert into books values('382', ' P. T. Barnum', 'The Art of Money Getting, or Golden Rules for Making Money', 'Accessible bookArtistes interprètesEntertainers');
Insert into books values('383', ' H. G. Wells', 'The War of the Worlds', 'Law, Anglo-SaxonWar and emergency legislationCorporation lawAccessible bookLegislation');
Insert into books values('384', ' Arthur Conan Doyle', 'The Valley of Fear (Sherlock Holmes #4)', 'forgescommissionairesgoldMystery & SuspenseConfederate States Army');
Insert into books values('385', ' Hume Nisbet', 'The Vampire Maid', 'Protected DAISYAccessible bookBuffy the Vampire Slayer (Fictitious character)VampiresFiction');
Insert into books values('386', ' Lyman Frank Baum', 'The Wonderful Wizard of Oz (The Oz Books #1)', 'Literature and fiction, juvenileYoung adult ');
Insert into books values('387', ' William Hope Hodgson', 'The Night Land', 'Man-woman relationshipsPlaysAccessible bookFictionMiniature books');
Insert into books values('388', ' Lucy Maud Montgomery', 'Anne of Green Gables (Anne Shirley Series #1)', 'Juvenile fiction');
Insert into books values('389', ' Marcus Aurelius', 'The Meditations', 'Accessible book');
Insert into books values('390', ' Fyodor Mikhailovich Dostoyevsky', 'The Double', 'Christian social thought & activityChristianity');
Insert into books values('391', ' Jules Verne', 'The Mysterious Island', 'French Science fictionFiction in EnglishProtected DAISYOpen Library Staff PicksSurvival');
Insert into books values('392', ' Jules Verne', 'A Journey into the Centre of the Earth', 'Earth (planet), internal structure');
Insert into books values('393', ' Charlotte BrontÃ«', 'Jane Eyre', 'Man-woman relationshipsReading Level-Grade 12');
Insert into books values('394', ' Jesse Franklin Bone', 'Pandemic', 'TornadoesAccessible bookDroughtsLandslidesJuvenile literature');
Insert into books values('395', ' Oscar Wilde', 'The Happy Prince and Other Tales', 'English Fantasy fictionLittérature irlandaiseStatuesConstancyJuvenile fiction');
Insert into books values('396', ' Virginia Woolf', 'A Haunted House', 'Haunted housesGhostsJuvenile literature');
Insert into books values('397', ' J.M. Barrie', 'Peter Pan (Peter and Wendy)', 'FantasyJuvenile fictionAccessible bookChildrens stories');
Insert into books values('398', ' Charles Dickens', 'The Schoolboys Story', 'Schools Friendship Fiction');
Insert into books values('445', ' William Shakespeare', 'Macbeth', 'Stage historyPlaysShakespeare, william');
Insert into books values('399', ' H. G. Wells', 'The Time Machine', 'Woodworking toolsWoodworking machinerySawsAccessible bookProtected DAISY');
Insert into books values('400', ' Jane Austen', 'Sense and Sensibility', 'Women authorsBibliographyWomen and literatureFiction');
Insert into books values('401', ' Mark Twain', 'The Prince and the Pauper', 'Adventure and adventurers');
Insert into books values('402', ' William Shakespeare', 'A Midsummer Nights Dream', 'World War, Plays English literature, study and teaching');
Insert into books values('443', ' Wilkie Collins', 'The Moonstone', 'Teenage boysInfluenza Epidemic, 1918-1919Fiction');
Insert into books values('403', ' Lev Nikolayevich Tolstoy', 'War and Peace', 'Law, Anglo-SaxonWar');
Insert into books values('404', ' Mark Twain', 'The Adventures of Huckleberry Finn', 'runaway teenagersAmerican manuscriptsHuckleberry FinnAnglais (langue)French');
Insert into books values('405', ' Robert Louis Stevenson', 'Treasure Island', 'RechercheTrésorsAccessible bookCocos Island Hydraulic and Treasure CompanyTreasure troves');
Insert into books values('406', ' H. P. Lovecraft', 'The Dunwich Horror', 'Cuentos de terror estadounidensesAccessible bookAmerican Horror talesProtected DAISY');
Insert into books values('407', ' Alexandre Dumas', 'The Three Musketeers (DArtagnan Romances #1)', 'Accessible book');
Insert into books values('408', ' Hendrik Antoon Lorentz', 'The Einstein Theory of Relativity', 'Accessible bookProtected DAISYRelativity (physics)Relativity (Physics)');
Insert into books values('409', ' Mark Twain', 'The Adventures of Tom Sawyer', 'Mark Twain');
Insert into books values('410', ' Friedrich Wilhelm Nietzsche', 'Beyond Good and Evil', 'Philosophy');
Insert into books values('411', ' Mary Shelley', 'Frankenstein', 'Frankenstein');
Insert into books values('412', ' Jack London', 'The Call of the Wild', 'Gold discoveri');
Insert into books values('413', ' Emily Bronte', 'Wuthering Heights', 'Interpersonal relations, fiction');
Insert into books values('414', ' Oscar Wilde', 'The Picture of Dorian Gray', 'AgingEnglish literatureDictionariesConduct of lifeDrama (dramatic works by one author)');
Insert into books values('415', ' Edgar Allen Poe', 'The Murders in the Rue Morgue', 'Paris (france), fictionFrance, fictionDupin, auguste (fictitious character), fiction');
Insert into books values('416', ' Mark Twain', 'Life on the Mississippi', 'Mississippi River American AuthorsFiction');
Insert into books values('417', ' H. G. Wells', 'A Modern Utopia', 'Modern AestheticsUtopiasEuropean ArtsUtopias in artAvant-garde (aesthetics)');
Insert into books values('418', ' Joseph Conrad', 'Heart of Darkness', 'SouffranceAccessible bookTravelHeart of darkness (Conrad, Joseph)Fiction');
Insert into books values('419', ' H. G. Wells', 'The Invisible Man', 'Mentally illPsychological fictionNational Book Award WinnerAccessible bookRacism');
Insert into books values('420', ' Arthur Conan Doyle', 'The Return of Sherlock Holmes', 'forgesransomsdetective fictionNihilismmurder-suicide');
Insert into books values('421', ' Alexandre Dumas', 'The Count of Monte Cristo', 'Fiction, action & adventure Continental european fiction ReadersAccessible bookFiction');
Insert into books values('422', ' Charles Dickens', 'A Tale of Two Cities', 'Executions and executionersAccessible bookPolitical refugeesFictionLANGUAGE & LITERARY STUDIES');
Insert into books values('423', ' Arthur Conan Doyle', 'A Study in Scarlet', 'Trichinopoly cigarshemoglobinAccessible bookFictionSecond Anglo-Afghan War');
Insert into books values('424', ' Prentice Mulford', 'Thoughts are Things', 'New AgeEssaysPhilosophyNonfictionSelf-Improvement');
Insert into books values('425', ' Washington Irving', 'The Legend of Sleepy Hollow', 'American fiction New york (state), fictionFiction, horrorFiction, ghost');
Insert into books values('426', ' Homer', 'The Iliad of Homer', 'Trojan War, (Greek mythology)Juvenile poetry');
Insert into books values('427', ' Gilbert Keith Chesterston', 'The Man Who Knew Too Much', 'Fiction, mystery & detective, generalAccessible (Social class)Fiction');
Insert into books values('428', ' E. M. Forster', 'A Room With a View', 'Interior decorationKips Bay Showhouse (Firm)History');
Insert into books values('429', ' Arthur Conan Doyle', 'The Hound of the Baskervilles', 'Sir1900-1945 TextArthur Conan DoyleAccessible bookEnglish');
Insert into books values('430', ' James Stephens', 'Irish Fairy Tales', 'FantasyYoung Adult FictionShort StoriesFolkloreFiction');
Insert into books values('431', ' Wilkie Collins', 'The Woman in White', 'Mentally illDeceptionAccessible bookCountry homesInheritance and succession');
Insert into books values('432', ' Fyodor Mikhailovich Dostoyevsky', 'The Brothers Karamazov', 'Novela rusaAccessible bookProtected DAISYCrítica e interpretación');
Insert into books values('433', ' David Herbert Lawrence', 'The Rainbow', 'Instruction and studyMusic');
Insert into books values('434', ' Edgar Allen Poe', 'The Raven', 'CorrespondencePoésie fantastique américaineAestheticsPoésie enfantine américaineAccessible book');
Insert into books values('435', ' Jack London', 'The Sea Wolf', 'Accessible book');
Insert into books values('436', ' Franz Kafka', 'The Metamorphosis', 'Accessible bookProtected DAISY');
Insert into books values('437', ' Thomas Hardy', 'Tess of the dUrbevilles', 'Graphic Fortnightly review National observer');
Insert into books values('444', ' John Cleland', 'Fanny Hill: Memoirs of a Woman of Pleasure', 'Accessible bookWomen in fiction');
Insert into books values('438', ' Lucius Apuleius', 'The Golden Ass', 'Classic Literatureopen_syllabus_projectFiction');
Insert into books values('439', ' James Joyce', 'Dubliners', 'ProtestantismHalloweenAccessible bookDomestic fictionReading Level-Grade 12');
Insert into books values('440', ' Jules Verne', 'An Antarctic Mystery', 'Southern OceanScience fictiontravelAntarcticaAccessible book');
Insert into books values('441', ' Edgar Rice Burroughs', 'The Gods of Mars', 'American Science fictionScience fiction, AmericanAccessible bookProtected DAISYFiction');
Insert into books values('442', ' Laozi', 'Tao Te Ching', 'Body, Mind & SpiritOuvrages avant 1800Accessible bookPeaceReligion');

INSERT INTO user VALUES('nchellani');
INSERT INTO user VALUES('sgurtata');
INSERT INTO user VALUES('awang');
INSERT INTO user VALUES('rstevens');
INSERT INTO user VALUES('igruters');
INSERT INTO user VALUES('eanderson');
INSERT INTO user VALUES('jmcdonald');
INSERT INTO user VALUES('czhou');
INSERT INTO user VALUES('bfache');
INSERT INTO user VALUES('sbhandari');
INSERT INTO user VALUES('naryal');
INSERT INTO user VALUES('sdhugana');
INSERT INTO user VALUES('kkhimani');
INSERT INTO user VALUES('asriram');
INSERT INTO user VALUES('scoheleach');
INSERT INTO user VALUES('sbhushan');
INSERT INTO user VALUES('jflores');
INSERT INTO user VALUES('amendoza');
INSERT INTO user VALUES('vrathnam');
INSERT INTO user VALUES('mphillips');
INSERT INTO user VALUES('agrudzin');
INSERT INTO user VALUES('jreger');
INSERT INTO user VALUES('rchellani');
INSERT INTO user VALUES('sqian');
INSERT INTO user VALUES('abrown');
INSERT INTO login VALUES('nchellani','nc123','nchellani@yahoo.com','22');
INSERT INTO login VALUES('sgurtata','sg123','sgurtata@gmail.com','22');
INSERT INTO login VALUES('awang','aw123','awang@hotmail.com','22');
INSERT INTO login VALUES('rstevens','rs123','rstevens@gmail.com','22');
INSERT INTO login VALUES('igruters','ig123','igruters@gmail.com','22');
INSERT INTO login VALUES('eanderson','ea123','eanderson@yahoo.com','22');
INSERT INTO login VALUES('jmcdonald','jm123','jmcdonald@gmail.com','22');
INSERT INTO login VALUES('czhou','cz123','czhou@gmail.com','22');
INSERT INTO login VALUES('bfache','bt123','bfache@gmail.com','22');
INSERT INTO login VALUES('sbhandari','sb123','sbhandari@gmail.com','22');
INSERT INTO login VALUES('naryal','na123','naryal@gmail.com','22');
INSERT INTO login VALUES('sdhugana','sd123','sdhugana@yahoo.com','22');
INSERT INTO login VALUES('kkhimani','kk123','kkhimani@yahoo.com','22');
INSERT INTO login VALUES('asriram','as123','asriram@gmail.com','22');
INSERT INTO login VALUES('scoheleach','sc123','scoheleach@gmail.com','22');
INSERT INTO login VALUES('sbhushan','sbh123','sbhushan@gmail.com','22');
INSERT INTO login VALUES('jflores','jf123','jflores@gmail.com','22');
INSERT INTO login VALUES('amendoza','am123','amendoza@yahoo.com','22');
INSERT INTO login VALUES('vrathnam','vr123','vrathnam@gmail.com','22');
INSERT INTO login VALUES('mphillips','mp123','mphillips@yahoo.com','22');
INSERT INTO login VALUES('agrudzin','ag123','agrudzinski@yahoo.com','22');
INSERT INTO login VALUES('jreger','jr123','jreger@gmail.com','22');
INSERT INTO login VALUES('rchellani','rc123','rchellani@gmail.com','22');
INSERT INTO login VALUES('sqian','sq123','sqian@yahoo.com','22');
INSERT INTO login VALUES('abrown','ab123','abrown@gmail.com','22');

INSERT INTO Likes VALUES('nchellani','380','Like');
INSERT INTO Likes VALUES('nchellani','367','Disike');
INSERT INTO Likes VALUES('nchellani','388','Like');
INSERT INTO Likes VALUES('nchellani','376','Disike');
INSERT INTO Likes VALUES('nchellani','393','Like');
INSERT INTO Likes VALUES('nchellani','413','Disike');
INSERT INTO Likes VALUES('nchellani','411','Like');
INSERT INTO Likes VALUES('sgurtata','367','Like');
INSERT INTO Likes VALUES('sgurtata','393','Like');
INSERT INTO Likes VALUES('sgurtata','445','Disike');
INSERT INTO Likes VALUES('sgurtata','402','Like');
INSERT INTO Likes VALUES('sgurtata','404','Disike');
INSERT INTO Likes VALUES('awang','368','Like');
INSERT INTO Likes VALUES('awang','437','Disike');
INSERT INTO Likes VALUES('awang','373','Like');
INSERT INTO Likes VALUES('awang','444','Disike');
INSERT INTO Likes VALUES('awang','383','Like');
INSERT INTO Likes VALUES('awang','438','Disike');
INSERT INTO Likes VALUES('awang','413','Like');
INSERT INTO Likes VALUES('awang','439','Disike');
INSERT INTO Likes VALUES('awang','414','Like');
INSERT INTO Likes VALUES('awang','440','Disike');
INSERT INTO Likes VALUES('awang','416','Like');
INSERT INTO Likes VALUES('awang','441','Disike');
INSERT INTO Likes VALUES('awang','417','Like');
INSERT INTO Likes VALUES('awang','442','Disike');
INSERT INTO Likes VALUES('awang','418','Like');
INSERT INTO Likes VALUES('awang','419','Like');
INSERT INTO Likes VALUES('awang','421','Like');
INSERT INTO Likes VALUES('awang','423','Like');
INSERT INTO Likes VALUES('awang','425','Like');
INSERT INTO Likes VALUES('awang','428','Like');
INSERT INTO Likes VALUES('awang','431','Like');
INSERT INTO Likes VALUES('rstevens','368','Like');
INSERT INTO Likes VALUES('rstevens','367','Disike');
INSERT INTO Likes VALUES('rstevens','374','Like');
INSERT INTO Likes VALUES('rstevens','380','Like');
INSERT INTO Likes VALUES('rstevens','371','Disike');
INSERT INTO Likes VALUES('rstevens','389','Like');
INSERT INTO Likes VALUES('rstevens','437','Disike');
INSERT INTO Likes VALUES('rstevens','414','Like');
INSERT INTO Likes VALUES('rstevens','418','Like');
INSERT INTO Likes VALUES('rstevens','420','Like');
INSERT INTO Likes VALUES('rstevens','421','Like');
INSERT INTO Likes VALUES('rstevens','427','Like');
INSERT INTO Likes VALUES('rstevens','429','Like');
INSERT INTO Likes VALUES('rstevens','432','Like');
INSERT INTO Likes VALUES('igruters','368','Like');
INSERT INTO Likes VALUES('igruters','420','Disike');
INSERT INTO Likes VALUES('igruters','371','Like');
INSERT INTO Likes VALUES('igruters','421','Disike');
INSERT INTO Likes VALUES('igruters','374','Like');
INSERT INTO Likes VALUES('igruters','423','Disike');
INSERT INTO Likes VALUES('igruters','385','Like');
INSERT INTO Likes VALUES('igruters','425','Disike');
INSERT INTO Likes VALUES('igruters','387','Like');
INSERT INTO Likes VALUES('igruters','434','Disike');
INSERT INTO Likes VALUES('igruters','399','Like');
INSERT INTO Likes VALUES('igruters','444','Disike');
INSERT INTO Likes VALUES('igruters','400','Like');
INSERT INTO Likes VALUES('igruters','443','Like');
INSERT INTO Likes VALUES('igruters','410','Like');
INSERT INTO Likes VALUES('igruters','412','Like');
INSERT INTO Likes VALUES('igruters','414','Like');
INSERT INTO Likes VALUES('igruters','419','Like');
INSERT INTO Likes VALUES('igruters','430','Like');
INSERT INTO Likes VALUES('igruters','431','Like');
INSERT INTO Likes VALUES('igruters','433','Like');
INSERT INTO Likes VALUES('eanderson','368','Like');
INSERT INTO Likes VALUES('eanderson','372','Disike');
INSERT INTO Likes VALUES('eanderson','373','Disike');
INSERT INTO Likes VALUES('eanderson','369','Like');
INSERT INTO Likes VALUES('eanderson','374','Disike');
INSERT INTO Likes VALUES('eanderson','375','Disike');
INSERT INTO Likes VALUES('eanderson','376','Disike');
INSERT INTO Likes VALUES('eanderson','377','Disike');
INSERT INTO Likes VALUES('eanderson','378','Disike');
INSERT INTO Likes VALUES('eanderson','379','Disike');
INSERT INTO Likes VALUES('jmcdonald','369','Like');
INSERT INTO Likes VALUES('jmcdonald','420','Disike');
INSERT INTO Likes VALUES('jmcdonald','385','Like');
INSERT INTO Likes VALUES('jmcdonald','421','Disike');
INSERT INTO Likes VALUES('jmcdonald','386','Like');
INSERT INTO Likes VALUES('jmcdonald','423','Disike');
INSERT INTO Likes VALUES('jmcdonald','387','Like');
INSERT INTO Likes VALUES('jmcdonald','425','Disike');
INSERT INTO Likes VALUES('jmcdonald','397','Like');
INSERT INTO Likes VALUES('jmcdonald','428','Disike');
INSERT INTO Likes VALUES('jmcdonald','398','Like');
INSERT INTO Likes VALUES('jmcdonald','429','Disike');
INSERT INTO Likes VALUES('jmcdonald','445','Like');
INSERT INTO Likes VALUES('jmcdonald','430','Disike');
INSERT INTO Likes VALUES('czhou','393','Like');
INSERT INTO Likes VALUES('czhou','367','Disike');
INSERT INTO Likes VALUES('czhou','405','Like');
INSERT INTO Likes VALUES('czhou','392','Disike');
INSERT INTO Likes VALUES('czhou','411','Like');
INSERT INTO Likes VALUES('czhou','404','Disike');
INSERT INTO Likes VALUES('czhou','418','Like');
INSERT INTO Likes VALUES('czhou','421','Like');
INSERT INTO Likes VALUES('bfache','380','Like');
INSERT INTO Likes VALUES('bfache','387','Disike');
INSERT INTO Likes VALUES('bfache','388','Like');
INSERT INTO Likes VALUES('bfache','392','Disike');
INSERT INTO Likes VALUES('bfache','397','Like');
INSERT INTO Likes VALUES('bfache','406','Disike');
INSERT INTO Likes VALUES('bfache','443','Like');
INSERT INTO Likes VALUES('bfache','410','Disike');
INSERT INTO Likes VALUES('bfache','414','Like');
INSERT INTO Likes VALUES('bfache','422','Disike');
INSERT INTO Likes VALUES('bfache','415','Like');
INSERT INTO Likes VALUES('bfache','428','Disike');
INSERT INTO Likes VALUES('bfache','429','Disike');
INSERT INTO Likes VALUES('bfache','430','Disike');
INSERT INTO Likes VALUES('bfache','431','Disike');
INSERT INTO Likes VALUES('sbhandari','373','Like');
INSERT INTO Likes VALUES('sbhandari','443','Disike');
INSERT INTO Likes VALUES('sbhandari','377','Like');
INSERT INTO Likes VALUES('sbhandari','409','Disike');
INSERT INTO Likes VALUES('sbhandari','378','Like');
INSERT INTO Likes VALUES('sbhandari','442','Disike');
INSERT INTO Likes VALUES('sbhandari','403','Like');
INSERT INTO Likes VALUES('sbhandari','408','Like');
INSERT INTO Likes VALUES('sbhandari','426','Like');
INSERT INTO Likes VALUES('sbhandari','437','Like');
INSERT INTO Likes VALUES('naryal','367','Like');
INSERT INTO Likes VALUES('naryal','374','Disike');
INSERT INTO Likes VALUES('naryal','378','Disike');
INSERT INTO Likes VALUES('naryal','369','Like');
INSERT INTO Likes VALUES('naryal','379','Disike');
INSERT INTO Likes VALUES('naryal','371','Like');
INSERT INTO Likes VALUES('naryal','380','Disike');
INSERT INTO Likes VALUES('naryal','375','Like');
INSERT INTO Likes VALUES('naryal','385','Disike');
INSERT INTO Likes VALUES('sdhugana','367','Like');
INSERT INTO Likes VALUES('sdhugana','370','Disike');
INSERT INTO Likes VALUES('sdhugana','380','Disike');
INSERT INTO Likes VALUES('sdhugana','373','Like');
INSERT INTO Likes VALUES('sdhugana','441','Disike');
INSERT INTO Likes VALUES('sdhugana','391','Like');
INSERT INTO Likes VALUES('sdhugana','442','Disike');
INSERT INTO Likes VALUES('sdhugana','400','Like');
INSERT INTO Likes VALUES('sdhugana','412','Like');
INSERT INTO Likes VALUES('sdhugana','418','Like');
INSERT INTO Likes VALUES('sdhugana','422','Like');
INSERT INTO Likes VALUES('kkhimani','367','Like');
INSERT INTO Likes VALUES('kkhimani','393','Like');
INSERT INTO Likes VALUES('kkhimani','404','Disike');
INSERT INTO Likes VALUES('kkhimani','402','Like');
INSERT INTO Likes VALUES('kkhimani','425','Disike');
INSERT INTO Likes VALUES('asriram','388','Like');
INSERT INTO Likes VALUES('asriram','367','Disike');
INSERT INTO Likes VALUES('asriram','393','Like');
INSERT INTO Likes VALUES('asriram','402','Disike');
INSERT INTO Likes VALUES('asriram','404','Like');
INSERT INTO Likes VALUES('asriram','418','Disike');
INSERT INTO Likes VALUES('asriram','409','Like');
INSERT INTO Likes VALUES('asriram','411','Like');
INSERT INTO Likes VALUES('scoheleach','368','Like');
INSERT INTO Likes VALUES('scoheleach','367','Disike');
INSERT INTO Likes VALUES('scoheleach','369','Like');
INSERT INTO Likes VALUES('scoheleach','373','Like');
INSERT INTO Likes VALUES('scoheleach','385','Disike');
INSERT INTO Likes VALUES('scoheleach','380','Like');
INSERT INTO Likes VALUES('scoheleach','386','Disike');
INSERT INTO Likes VALUES('scoheleach','392','Like');
INSERT INTO Likes VALUES('scoheleach','404','Disike');
INSERT INTO Likes VALUES('scoheleach','400','Like');
INSERT INTO Likes VALUES('scoheleach','412','Disike');
INSERT INTO Likes VALUES('scoheleach','402','Like');
INSERT INTO Likes VALUES('scoheleach','413','Disike');
INSERT INTO Likes VALUES('scoheleach','405','Like');
INSERT INTO Likes VALUES('scoheleach','416','Disike');
INSERT INTO Likes VALUES('scoheleach','411','Like');
INSERT INTO Likes VALUES('scoheleach','419','Disike');
INSERT INTO Likes VALUES('scoheleach','414','Like');
INSERT INTO Likes VALUES('scoheleach','422','Disike');
INSERT INTO Likes VALUES('scoheleach','415','Like');
INSERT INTO Likes VALUES('scoheleach','435','Disike');
INSERT INTO Likes VALUES('scoheleach','420','Like');
INSERT INTO Likes VALUES('scoheleach','425','Like');
INSERT INTO Likes VALUES('scoheleach','429','Like');
INSERT INTO Likes VALUES('scoheleach','434','Like');
INSERT INTO Likes VALUES('scoheleach','440','Like');
INSERT INTO Likes VALUES('sbhushan','367','Like');
INSERT INTO Likes VALUES('sbhushan','378','Disike');
INSERT INTO Likes VALUES('sbhushan','369','Like');
INSERT INTO Likes VALUES('sbhushan','445','Disike');
INSERT INTO Likes VALUES('sbhushan','373','Like');
INSERT INTO Likes VALUES('sbhushan','400','Disike');
INSERT INTO Likes VALUES('sbhushan','377','Like');
INSERT INTO Likes VALUES('sbhushan','409','Disike');
INSERT INTO Likes VALUES('sbhushan','380','Like');
INSERT INTO Likes VALUES('sbhushan','413','Disike');
INSERT INTO Likes VALUES('sbhushan','404','Like');
INSERT INTO Likes VALUES('sbhushan','434','Like');
INSERT INTO Likes VALUES('jflores','368','Like');
INSERT INTO Likes VALUES('jflores','367','Disike');
INSERT INTO Likes VALUES('jflores','378','Disike');
INSERT INTO Likes VALUES('jflores','369','Like');
INSERT INTO Likes VALUES('jflores','382','Disike');
INSERT INTO Likes VALUES('jflores','371','Like');
INSERT INTO Likes VALUES('jflores','386','Disike');
INSERT INTO Likes VALUES('jflores','373','Like');
INSERT INTO Likes VALUES('jflores','403','Disike');
INSERT INTO Likes VALUES('jflores','376','Like');
INSERT INTO Likes VALUES('jflores','405','Disike');
INSERT INTO Likes VALUES('jflores','380','Like');
INSERT INTO Likes VALUES('jflores','388','Like');
INSERT INTO Likes VALUES('jflores','396','Like');
INSERT INTO Likes VALUES('jflores','397','Like');
INSERT INTO Likes VALUES('jflores','445','Like');
INSERT INTO Likes VALUES('jflores','402','Like');
INSERT INTO Likes VALUES('jflores','404','Like');
INSERT INTO Likes VALUES('jflores','407','Like');
INSERT INTO Likes VALUES('jflores','409','Like');
INSERT INTO Likes VALUES('jflores','411','Like');
INSERT INTO Likes VALUES('jflores','412','Like');
INSERT INTO Likes VALUES('jflores','413','Like');
INSERT INTO Likes VALUES('amendoza','367','Like');
INSERT INTO Likes VALUES('amendoza','370','Disike');
INSERT INTO Likes VALUES('amendoza','390','Disike');
INSERT INTO Likes VALUES('amendoza','369','Like');
INSERT INTO Likes VALUES('amendoza','418','Disike');
INSERT INTO Likes VALUES('amendoza','371','Like');
INSERT INTO Likes VALUES('amendoza','373','Like');
INSERT INTO Likes VALUES('amendoza','377','Like');
INSERT INTO Likes VALUES('amendoza','391','Like');
INSERT INTO Likes VALUES('amendoza','392','Like');
INSERT INTO Likes VALUES('amendoza','396','Like');
INSERT INTO Likes VALUES('amendoza','397','Like');
INSERT INTO Likes VALUES('amendoza','445','Like');
INSERT INTO Likes VALUES('amendoza','404','Like');
INSERT INTO Likes VALUES('amendoza','407','Like');
INSERT INTO Likes VALUES('amendoza','409','Like');
INSERT INTO Likes VALUES('amendoza','421','Like');
INSERT INTO Likes VALUES('amendoza','422','Like');
INSERT INTO Likes VALUES('amendoza','425','Like');
INSERT INTO Likes VALUES('amendoza','426','Like');
INSERT INTO Likes VALUES('vrathnam','368','Like');
INSERT INTO Likes VALUES('vrathnam','367','Disike');
INSERT INTO Likes VALUES('vrathnam','372','Like');
INSERT INTO Likes VALUES('vrathnam','369','Disike');
INSERT INTO Likes VALUES('vrathnam','375','Like');
INSERT INTO Likes VALUES('vrathnam','378','Disike');
INSERT INTO Likes VALUES('vrathnam','445','Disike');
INSERT INTO Likes VALUES('vrathnam','383','Like');
INSERT INTO Likes VALUES('vrathnam','402','Disike');
INSERT INTO Likes VALUES('vrathnam','386','Like');
INSERT INTO Likes VALUES('vrathnam','392','Like');
INSERT INTO Likes VALUES('vrathnam','399','Like');
INSERT INTO Likes VALUES('vrathnam','403','Like');
INSERT INTO Likes VALUES('vrathnam','405','Like');
INSERT INTO Likes VALUES('vrathnam','419','Like');
INSERT INTO Likes VALUES('vrathnam','420','Like');
INSERT INTO Likes VALUES('vrathnam','422','Like');
INSERT INTO Likes VALUES('vrathnam','426','Like');
INSERT INTO Likes VALUES('mphillips','367','Disike');
INSERT INTO Likes VALUES('mphillips','380','Like');
INSERT INTO Likes VALUES('mphillips','373','Disike');
INSERT INTO Likes VALUES('mphillips','386','Like');
INSERT INTO Likes VALUES('mphillips','411','Disike');
INSERT INTO Likes VALUES('mphillips','415','Like');
INSERT INTO Likes VALUES('mphillips','422','Like');
INSERT INTO Likes VALUES('agrudzin','367','Like');
INSERT INTO Likes VALUES('agrudzin','404','Disike');
INSERT INTO Likes VALUES('agrudzin','386','Like');
INSERT INTO Likes VALUES('agrudzin','426','Disike');
INSERT INTO Likes VALUES('agrudzin','402','Like');
INSERT INTO Likes VALUES('agrudzin','432','Disike');
INSERT INTO Likes VALUES('agrudzin','422','Like');
INSERT INTO Likes VALUES('agrudzin','425','Like');
INSERT INTO Likes VALUES('jreger','369','Like');
INSERT INTO Likes VALUES('jreger','367','Disike');
INSERT INTO Likes VALUES('jreger','389','Like');
INSERT INTO Likes VALUES('jreger','445','Like');
INSERT INTO Likes VALUES('jreger','397','Disike');
INSERT INTO Likes VALUES('jreger','399','Like');
INSERT INTO Likes VALUES('jreger','434','Disike');
INSERT INTO Likes VALUES('jreger','400','Like');
INSERT INTO Likes VALUES('jreger','426','Like');
INSERT INTO Likes VALUES('rchellani','368','Like');
INSERT INTO Likes VALUES('rchellani','367','Disike');
INSERT INTO Likes VALUES('rchellani','369','Disike');
INSERT INTO Likes VALUES('rchellani','373','Like');
INSERT INTO Likes VALUES('rchellani','376','Disike');
INSERT INTO Likes VALUES('rchellani','375','Like');
INSERT INTO Likes VALUES('rchellani','378','Disike');
INSERT INTO Likes VALUES('rchellani','380','Like');
INSERT INTO Likes VALUES('rchellani','386','Like');
INSERT INTO Likes VALUES('rchellani','400','Disike');
INSERT INTO Likes VALUES('rchellani','388','Like');
INSERT INTO Likes VALUES('rchellani','402','Disike');
INSERT INTO Likes VALUES('rchellani','392','Like');
INSERT INTO Likes VALUES('rchellani','404','Disike');
INSERT INTO Likes VALUES('rchellani','393','Like');
INSERT INTO Likes VALUES('rchellani','407','Disike');
INSERT INTO Likes VALUES('rchellani','396','Like');
INSERT INTO Likes VALUES('rchellani','409','Disike');
INSERT INTO Likes VALUES('rchellani','445','Like');
INSERT INTO Likes VALUES('rchellani','425','Disike');
INSERT INTO Likes VALUES('rchellani','408','Like');
INSERT INTO Likes VALUES('rchellani','426','Disike');
INSERT INTO Likes VALUES('rchellani','411','Like');
INSERT INTO Likes VALUES('rchellani','413','Like');
INSERT INTO Likes VALUES('rchellani','414','Like');
INSERT INTO Likes VALUES('rchellani','420','Like');
INSERT INTO Likes VALUES('rchellani','421','Like');
INSERT INTO Likes VALUES('rchellani','422','Like');
INSERT INTO Likes VALUES('rchellani','423','Like');
INSERT INTO Likes VALUES('rchellani','429','Like');
INSERT INTO Likes VALUES('rchellani','434','Like');
INSERT INTO Likes VALUES('rchellani','441','Like');
INSERT INTO Likes VALUES('sqian','367','Like');
INSERT INTO Likes VALUES('sqian','371','Disike');
INSERT INTO Likes VALUES('sqian','372','Disike');
INSERT INTO Likes VALUES('sqian','374','Like');
INSERT INTO Likes VALUES('sqian','373','Disike');
INSERT INTO Likes VALUES('sqian','376','Like');
INSERT INTO Likes VALUES('sqian','375','Disike');
INSERT INTO Likes VALUES('sqian','380','Like');
INSERT INTO Likes VALUES('sqian','378','Disike');
INSERT INTO Likes VALUES('sqian','393','Like');
INSERT INTO Likes VALUES('sqian','400','Like');
INSERT INTO Likes VALUES('sqian','383','Disike');
INSERT INTO Likes VALUES('sqian','413','Like');
INSERT INTO Likes VALUES('sqian','392','Disike');
INSERT INTO Likes VALUES('sqian','414','Like');
INSERT INTO Likes VALUES('sqian','445','Disike');
INSERT INTO Likes VALUES('sqian','422','Like');
INSERT INTO Likes VALUES('sqian','399','Disike');
INSERT INTO Likes VALUES('sqian','408','Disike');
INSERT INTO Likes VALUES('sqian','409','Disike');
INSERT INTO Likes VALUES('sqian','426','Disike');
INSERT INTO Likes VALUES('abrown','368','Like');
INSERT INTO Likes VALUES('abrown','367','Disike');
INSERT INTO Likes VALUES('abrown','372','Like');
INSERT INTO Likes VALUES('abrown','369','Disike');
INSERT INTO Likes VALUES('abrown','373','Like');
INSERT INTO Likes VALUES('abrown','370','Disike');
INSERT INTO Likes VALUES('abrown','375','Like');
INSERT INTO Likes VALUES('abrown','376','Disike');
INSERT INTO Likes VALUES('abrown','377','Like');
INSERT INTO Likes VALUES('abrown','380','Disike');
INSERT INTO Likes VALUES('abrown','388','Disike');
INSERT INTO Likes VALUES('abrown','383','Like');
INSERT INTO Likes VALUES('abrown','393','Disike');
INSERT INTO Likes VALUES('abrown','386','Like');
INSERT INTO Likes VALUES('abrown','411','Disike');
INSERT INTO Likes VALUES('abrown','394','Like');
INSERT INTO Likes VALUES('abrown','413','Disike');
INSERT INTO Likes VALUES('abrown','397','Like');
INSERT INTO Likes VALUES('abrown','445','Like');
INSERT INTO Likes VALUES('abrown','403','Like');
INSERT INTO Likes VALUES('abrown','407','Like');
INSERT INTO Likes VALUES('abrown','408','Like');
INSERT INTO Likes VALUES('abrown','409','Like');
INSERT INTO Likes VALUES('abrown','420','Like');
INSERT INTO Likes VALUES('abrown','425','Like');
INSERT INTO Likes VALUES('abrown','426','Like');
INSERT INTO Likes VALUES('abrown','434','Like');

INSERT INTO Reads_ VALUES ('nchellani','380');
INSERT INTO Reads_ VALUES ('nchellani','388');
INSERT INTO Reads_ VALUES ('sgurtata','445');
INSERT INTO Reads_ VALUES ('sgurtata','402');
INSERT INTO Reads_ VALUES ('sgurtata','404');
INSERT INTO Reads_ VALUES ('awang','373');
INSERT INTO Reads_ VALUES ('awang','383');
INSERT INTO Reads_ VALUES ('awang','413');
INSERT INTO Reads_ VALUES ('rstevens','368');
INSERT INTO Reads_ VALUES ('rstevens','374');
INSERT INTO Reads_ VALUES ('rstevens','380');
INSERT INTO Reads_ VALUES ('igruters','368');
INSERT INTO Reads_ VALUES ('igruters','371');
INSERT INTO Reads_ VALUES ('igruters','374');
INSERT INTO Reads_ VALUES ('igruters','385');
INSERT INTO Reads_ VALUES ('eanderson','368');
INSERT INTO Reads_ VALUES ('eanderson','369');
INSERT INTO Reads_ VALUES ('jmcdonald','369');
INSERT INTO Reads_ VALUES ('jmcdonald','385');
INSERT INTO Reads_ VALUES ('jmcdonald','386');
INSERT INTO Reads_ VALUES ('jmcdonald','387');
INSERT INTO Reads_ VALUES ('czhou','393');
INSERT INTO Reads_ VALUES ('czhou','405');
INSERT INTO Reads_ VALUES ('czhou','411');
INSERT INTO Reads_ VALUES ('bfache','380');
INSERT INTO Reads_ VALUES ('bfache','388');
INSERT INTO Reads_ VALUES ('bfache','397');
INSERT INTO Reads_ VALUES ('bfache','443');
INSERT INTO Reads_ VALUES ('bfache','414');
INSERT INTO Reads_ VALUES ('sbhandari','373');
INSERT INTO Reads_ VALUES ('sbhandari','377');
INSERT INTO Reads_ VALUES ('sbhandari','378');
INSERT INTO Reads_ VALUES ('sbhandari','403');
INSERT INTO Reads_ VALUES ('naryal','367');
INSERT INTO Reads_ VALUES ('naryal','369');
INSERT INTO Reads_ VALUES ('naryal','371');
INSERT INTO Reads_ VALUES ('naryal','375');
INSERT INTO Reads_ VALUES ('sdhugana','367');
INSERT INTO Reads_ VALUES ('sdhugana','373');
INSERT INTO Reads_ VALUES ('sdhugana','391');
INSERT INTO Reads_ VALUES ('sdhugana','400');
INSERT INTO Reads_ VALUES ('kkhimani','367');
INSERT INTO Reads_ VALUES ('kkhimani','393');
INSERT INTO Reads_ VALUES ('kkhimani','402');
INSERT INTO Reads_ VALUES ('kkhimani','404');
INSERT INTO Reads_ VALUES ('asriram','388');
INSERT INTO Reads_ VALUES ('asriram','393');
INSERT INTO Reads_ VALUES ('asriram','404');
INSERT INTO Reads_ VALUES ('scoheleach','368');
INSERT INTO Reads_ VALUES ('scoheleach','369');
INSERT INTO Reads_ VALUES ('scoheleach','373');
INSERT INTO Reads_ VALUES ('scoheleach','380');
INSERT INTO Reads_ VALUES ('sbhushan','367');
INSERT INTO Reads_ VALUES ('sbhushan','369');
INSERT INTO Reads_ VALUES ('sbhushan','373');
INSERT INTO Reads_ VALUES ('sbhushan','377');
INSERT INTO Reads_ VALUES ('sbhushan','380');
INSERT INTO Reads_ VALUES ('sbhushan','404');
INSERT INTO Reads_ VALUES ('jflores','368');
INSERT INTO Reads_ VALUES ('jflores','369');
INSERT INTO Reads_ VALUES ('jflores','371');
INSERT INTO Reads_ VALUES ('jflores','373');
INSERT INTO Reads_ VALUES ('jflores','376');
INSERT INTO Reads_ VALUES ('amendoza','367');
INSERT INTO Reads_ VALUES ('amendoza','369');
INSERT INTO Reads_ VALUES ('amendoza','371');
INSERT INTO Reads_ VALUES ('amendoza','373');
INSERT INTO Reads_ VALUES ('amendoza','377');
INSERT INTO Reads_ VALUES ('vrathnam','368');
INSERT INTO Reads_ VALUES ('vrathnam','372');
INSERT INTO Reads_ VALUES ('vrathnam','375');
INSERT INTO Reads_ VALUES ('mphillips','380');
INSERT INTO Reads_ VALUES ('mphillips','386');
INSERT INTO Reads_ VALUES ('mphillips','415');
INSERT INTO Reads_ VALUES ('agrudzin','367');
INSERT INTO Reads_ VALUES ('agrudzin','386');
INSERT INTO Reads_ VALUES ('agrudzin','402');
INSERT INTO Reads_ VALUES ('agrudzin','422');
INSERT INTO Reads_ VALUES ('agrudzin','425');
INSERT INTO Reads_ VALUES ('jreger','369');
INSERT INTO Reads_ VALUES ('jreger','389');
INSERT INTO Reads_ VALUES ('jreger','445');
INSERT INTO Reads_ VALUES ('jreger','399');
INSERT INTO Reads_ VALUES ('rchellani','368');
INSERT INTO Reads_ VALUES ('rchellani','373');
INSERT INTO Reads_ VALUES ('rchellani','375');
INSERT INTO Reads_ VALUES ('sqian','367');
INSERT INTO Reads_ VALUES ('sqian','374');
INSERT INTO Reads_ VALUES ('sqian','376');
INSERT INTO Reads_ VALUES ('abrown','368');
INSERT INTO Reads_ VALUES ('abrown','372');
INSERT INTO Reads_ VALUES ('abrown','373');
INSERT INTO Reads_ VALUES ('abrown','375');

INSERT INTO post (username, text1, book_id) VALUES ('bfache', 'I really enjoyed Anne’s journey from the beginning to the end. Despite the book having little overarching plot, Anne clearly matured by the end, demonstrated by her newfound friendship with Gilbert and reaction to Matthew’s death.', '388');
INSERT INTO post (username, text1, book_id) VALUES ('nchellani', 'I found it upsetting that Anne, and therefore the reader, was supposed to like Mrs. Lynde, who was highly judgmental and used religion as a way to condemn people she disliked or disagreed with.','388');
INSERT INTO post (username, text1, book_id) VALUES ('asriram', 'I liked that Anne and Diana’s friendship was balanced between being lighthearted and serious, as well as that Anne gave up trying to change her friend to be more like her.','388');
INSERT INTO post (username, text1, book_id) VALUES ('nchellani', 'I was surprised by how strongly the residents of Avonlea reacted to Anne’s arrival, as if a child had no worth at all; it was odd that the reader was supposed to sympathize with these characters later on.', '388');
INSERT INTO post (username, text1, book_id) VALUES ('czhou', 'I admire Jane’s integrity in spite of difficult circumstances after finding out about Bertha, but I think she was too kind to St. John. I was appalled by how well she received his proposal when he clearly did not have her best interests in mind.','393');
INSERT INTO post (username, text1, book_id) VALUES ('kkhimani', 'While I overall dislike Rochester, I liked how he changed by the time Jane returned, even if it was not by choice. It allowed their relationship to be one on equal terms rather than one based on authority.','393');
INSERT INTO post (username, text1, book_id) VALUES ('asriram', 'It really bothered me how manipulative Rochester was of Jane, and how much he expected of her. He hid his marriage from her and lied about Blanche, yet still expected her to marry him; this contradicted the book’s otherwise feminist themes.','393');
INSERT INTO post (username, text1, book_id) VALUES ('czhou', 'I like the way Helen’s death was handled. Even though one of the only sympathetic characters died, it taught Jane an important lesson that helped her mature into who she became at Thornfield Hall.', '393');
INSERT INTO post (username, text1, book_id) VALUES ('scoheleach', 'I found Meg to have very little discernible personality. What she did have came only through her relationships with others, and she was generally a static character.', '380');
INSERT INTO post (username, text1, book_id) VALUES ('sbhushan', 'I liked how much Jo grew from Beth’s death, and that it served a significant purpose rather than just being a randomly inserted plot point. Losing her closest sibling instilled a sense of purpose in her that helped her for the rest of her life.', '380');
INSERT INTO post (username, text1, book_id) VALUES ('mphillips', 'Despite her vanity and selfishness, I really liked Amy as a character. Her insistence on pursuing art and hardworking nature makes her more than her flaws, and perhaps the most nuanced of all the March sisters.', '380');
INSERT INTO post (username, text1, book_id) VALUES ('nchellani', 'Jo was my favorite March sister; I liked that she was a highly flawed yet independent, likeable character. Her transformation was also the most drastic, and I loved that her relationship with her sisters influenced her so positively.', '380');
